name: Build AnalyzeHelper
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Install window manage
        run: apt-get install ubuntu-desktop
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew clean runIde --debug
          options: "-ac -screen 0 1920x1080x24"