name: Build AnalyzeHelper
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: sudo apt-get install xvfb
      - name: Run xvfb
        run: Xvfb :99 -s -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &
      - name: Run performance test
        run: export DISPLAY=':99.0' && ./gradlew runIde --debug
#      - name: Install xwd
#        run: sudo apt-get install x11-apps
#      - name: Take screenshot
#        run: xwd -display :99.0 -root -silent | convert xwd:- png:/home/runner/work/analyze-helper-plugin/analyze-helper-plugin/build/idea-sandbox/system/log/screenshot.png
      - uses: actions/upload-artifact@v2
        with:
         name: idee-logs
         path: log