name: Build AnalyzeHelper
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: GabrielBB/xvfb-action@v1
        with:
          run: xvfb-run -s -ac -screen 0 1920x1080x24 --auto-servernum ./gradlew runIde --debug