name: Build AnalyzeHelper
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: sudo apt-get install xvfb
      - name: Run xvfb
        run: Xvfb :99 -s -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &
      - name: Build with Gradle
        run: export DISPLAY=':99.0' && env && ./gradlew runIde --stacktrace